#!/usr/bin/env python3
"""
docx-generator.py — Mode D Investment Memo DOCX Generator

Reads a run-local analysis-result.json and produces a professionally formatted
Word document (.docx) with all 10 sections, financial tables, and source tags.

Usage:
    python docx-generator.py
    python docx-generator.py --input output/runs/<run_id>/<ticker>/analysis-result.json
    python docx-generator.py --input output/runs/<run_id>/<ticker>/analysis-result.json --output output/reports/AAPL_D_EN_2026-03-12.docx
"""

import json
import sys
import os
import pathlib
import argparse
from datetime import datetime

try:
    from docx import Document
    from docx.shared import Pt, Inches, RGBColor, Cm
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.oxml.ns import qn
    from docx.oxml import OxmlElement
except ImportError:
    print("ERROR: python-docx not installed.")
    print("Run: pip install python-docx")
    sys.exit(1)


# ---------------------------------------------------------------------------
# Style helpers
# ---------------------------------------------------------------------------

COLOR_HEADER_BG   = "C6D9F1"   # Table header: light blue
COLOR_ROW_ALT     = "EEF4FB"   # Alternating row: very light blue
COLOR_TITLE_TEXT  = RGBColor(0x1A, 0x1A, 0x2E)
COLOR_SECTION     = RGBColor(0x16, 0x21, 0x3E)
COLOR_DISCLAIMER  = RGBColor(0x66, 0x66, 0x66)
COLOR_GENERATED   = RGBColor(0x99, 0x99, 0x99)

SECTION_HEADERS = {
    "en": {
        "exec":      "Executive Summary",
        "s1":        "1. Business Overview & Competitive Position",
        "s2":        "2. Financial Performance",
        "s2_rev":    "Revenue Trend (Last 8 Quarters)",
        "s2_margin": "Profitability Trend",
        "s2_cf":     "Cash Flow Analysis",
        "s2_bs":     "Balance Sheet Snapshot",
        "s3":        "3. Valuation Analysis",
        "s3_core":   "Core Valuation Metrics",
        "s3_sotp":   "Sum-of-the-Parts (SOTP) Analysis",
        "s4":        "4. 5-Question Variant View",
        "q1":        "Q1: What Is the Market Currently Pricing In — and Where Do We Disagree?",
        "q2":        "Q2: What Would Change the Market's Mind? (Catalyst Map)",
        "q3":        "Q3: What Optionality Is the Market Not Pricing In?",
        "q4":        "Q4: Capital Allocation — How Is Management Creating (or Destroying) Value?",
        "q5":        "Q5: Exit Conditions — When Would We Close the Position?",
        "s5":        "5. Precision Risk Analysis",
        "s5_macro":  "Macro Risk Overlay",
        "s6":        "6. Investment Scenarios",
        "s7":        "7. Peer Comparison",
        "s8":        "8. Management & Corporate Governance",
        "s9":        "9. Quality of Earnings (QoE) Assessment",
        "s9_bridge": "EBITDA Bridge",
        "s10":       "10. What Would Make Me Wrong",
        "appendix":  "Appendix: Data Sources & Confidence",
        "verdict_label":  "Verdict",
        "rr_label":       "R/R Score",
        "price_label":    "Current Price",
        "target_label":   "Base Case Target",
        "horizon_label":  "Investment Horizon",
        "prob_row":       "Probability",
        "target_row":     "Price Target",
        "return_row":     "Implied Return",
        "assumption_row": "Key Assumption",
        "bull":      "Bull Case",
        "base":      "Base Case",
        "bear":      "Bear Case",
        "disclaimer": (
            "Disclaimer: This investment memo is generated by an AI research assistant "
            "for informational purposes only. It does not constitute investment advice, "
            "a recommendation to buy or sell any security, or a guarantee of investment "
            "returns. All projections are hypothetical and based on available public "
            "information. Actual results may differ materially. This memo is not a "
            "substitute for professional financial advice. Always conduct your own research "
            "and consult a qualified financial advisor before making investment decisions."
        ),
    },
    "ko": {
        "exec":      "개요",
        "s1":        "1. 사업 개요 및 경쟁 위치",
        "s2":        "2. 재무 성과",
        "s2_rev":    "매출 추이 (최근 8분기)",
        "s2_margin": "수익성 추이",
        "s2_cf":     "현금흐름 분석",
        "s2_bs":     "재무상태표 요약",
        "s3":        "3. 밸류에이션 분석",
        "s3_core":   "핵심 밸류에이션 지표",
        "s3_sotp":   "부문별 가치 합산 (SOTP) 분석",
        "s4":        "4. 5가지 차별적 관점",
        "q1":        "Q1: 시장이 현재 가격에 반영하는 것 — 그리고 우리의 견해 차이",
        "q2":        "Q2: 시장의 견해를 바꿀 요인은? (카탈리스트 맵)",
        "q3":        "Q3: 시장이 아직 가격에 반영하지 않은 옵셔널리티는?",
        "q4":        "Q4: 자본 배분 — 경영진은 가치를 창출하는가, 파괴하는가?",
        "q5":        "Q5: 청산 조건 — 언제 포지션을 청산할 것인가?",
        "s5":        "5. 정밀 리스크 분석",
        "s5_macro":  "거시 리스크",
        "s6":        "6. 투자 시나리오",
        "s7":        "7. 동종업계 비교",
        "s8":        "8. 경영진 및 기업 지배구조",
        "s9":        "9. 이익의 질 평가",
        "s9_bridge": "EBITDA 브릿지",
        "s10":       "10. 내가 틀릴 경우",
        "appendix":  "부록: 데이터 출처 및 신뢰도",
        "verdict_label":  "투자의견",
        "rr_label":       "위험보상비율",
        "price_label":    "현재가",
        "target_label":   "기본 시나리오 목표가",
        "horizon_label":  "투자 기간",
        "prob_row":       "확률",
        "target_row":     "목표가",
        "return_row":     "예상 수익률",
        "assumption_row": "핵심 가정",
        "bull":      "강세 시나리오",
        "base":      "기본 시나리오",
        "bear":      "약세 시나리오",
        "disclaimer": (
            "면책 조항: 이 보고서는 정보 제공 목적으로만 AI 리서치 어시스턴트가 생성한 것입니다. "
            "투자 조언, 증권 매수/매도 권유, 또는 투자 수익 보장이 아닙니다. 모든 데이터는 공개 정보에서 "
            "수집되었으며 최신 시장 상황을 반영하지 않을 수 있습니다. 과거 실적이 미래 결과를 보장하지 "
            "않습니다. 투자 결정 전 반드시 자체 실사를 수행하고 전문 재무 어드바이저와 상담하시기 바랍니다."
        ),
    },
}


def _h(lang: str, key: str) -> str:
    """Get section header string for the given language."""
    return SECTION_HEADERS.get(lang, SECTION_HEADERS["en"]).get(key, key)


def set_cell_bg(cell, hex_color: str):
    """Set background fill color of a table cell."""
    tc = cell._tc
    tcPr = tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"), hex_color)
    tcPr.append(shd)


def add_heading(doc, text: str, level: int = 1):
    """Add a styled heading."""
    h = doc.add_heading(text, level=level)
    for run in h.runs:
        run.font.color.rgb = COLOR_TITLE_TEXT if level == 0 else COLOR_SECTION
        run.font.size = Pt({0: 20, 1: 14, 2: 12, 3: 11}.get(level, 11))
    return h


def add_table(doc, headers: list, rows: list):
    """Add a formatted table. Returns the table object."""
    if not rows:
        doc.add_paragraph("[데이터 없음 / No data available]")
        return None

    n_cols = len(headers)
    table = doc.add_table(rows=len(rows) + 1, cols=n_cols)
    table.style = "Table Grid"

    # Header row
    hdr = table.rows[0]
    for i, h in enumerate(headers):
        cell = hdr.cells[i]
        cell.text = str(h)
        set_cell_bg(cell, COLOR_HEADER_BG)
        for run in cell.paragraphs[0].runs:
            run.bold = True
            run.font.size = Pt(9)
        cell.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Data rows
    for r_idx, row_data in enumerate(rows):
        row = table.rows[r_idx + 1]
        for c_idx, val in enumerate(row_data[:n_cols]):
            cell = row.cells[c_idx]
            text = "—" if val is None else str(val)
            cell.text = text
            # Alternate shading
            if r_idx % 2 == 1:
                set_cell_bg(cell, COLOR_ROW_ALT)
            for run in cell.paragraphs[0].runs:
                run.font.size = Pt(9)

    doc.add_paragraph()
    return table


def add_text_block(doc, text, split_paras=True):
    """Add a text block, optionally splitting on double newlines."""
    if not text:
        return
    if isinstance(text, list):
        for item in text:
            add_text_block(doc, item, split_paras)
        return
    text = str(text).strip()
    if not text:
        return
    if split_paras:
        for para in text.split("\n\n"):
            p = para.strip()
            if p:
                doc.add_paragraph(p)
    else:
        doc.add_paragraph(text)


def dict_table(doc, data_dict: dict, key_label="Item", val_label="Value"):
    """Render a simple dict as a 2-column table."""
    rows = [[k.replace("_", " ").title(), v] for k, v in data_dict.items() if v is not None]
    add_table(doc, [key_label, val_label], rows)


def rows_from_list_of_dicts(records):
    """Convert list-of-dicts to (headers, rows) tuple."""
    if not records or not isinstance(records[0], dict):
        return [], []
    headers = [k.replace("_", " ").title() for k in records[0].keys()]
    rows = [[str(rec.get(k, "—") or "—") for k in records[0].keys()] for rec in records]
    return headers, rows


# ---------------------------------------------------------------------------
# Main document builder
# ---------------------------------------------------------------------------

def generate_docx(data: dict, output_path: str) -> str:
    lang = data.get("output_language", "en").lower()
    if lang not in ("ko", "en"):
        lang = "en"
    L = SECTION_HEADERS[lang]

    doc = Document()

    # Page margins
    sec = doc.sections[0]
    sec.page_width  = Inches(8.5)
    sec.page_height = Inches(11)
    for attr in ("left_margin", "right_margin", "top_margin", "bottom_margin"):
        setattr(sec, attr, Inches(1))

    ticker       = data.get("ticker", "N/A")
    company_name = data.get("company_name", ticker)
    analysis_date = data.get("analysis_date", datetime.now().strftime("%Y-%m-%d"))
    price        = data.get("price_at_analysis", "—")
    currency     = data.get("currency", "USD")
    rr_score     = data.get("rr_score", "—")
    verdict      = data.get("verdict", "—")
    data_mode    = data.get("data_mode", "standard")
    sections     = data.get("sections", {})

    cur_sym = "₩" if currency == "KRW" else "$"

    # -----------------------------------------------------------------------
    # TITLE BLOCK
    # -----------------------------------------------------------------------
    title = doc.add_heading("Investment Memo", 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    sub = doc.add_paragraph()
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = sub.add_run(f"{company_name}  ({ticker})")
    r.bold = True
    r.font.size = Pt(18)
    r.font.color.rgb = COLOR_TITLE_TEXT

    meta = doc.add_paragraph()
    meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
    price_fmt = (
        f"{cur_sym}{price:,.0f}" if currency == "KRW" and isinstance(price, (int, float))
        else f"{cur_sym}{price:,.2f}" if isinstance(price, (int, float))
        else f"{cur_sym}{price}"
    )
    meta.add_run(f"Date: {analysis_date}  |  Price: {price_fmt}  |  Mode: {data_mode.upper()}")

    vp = doc.add_paragraph()
    vp.alignment = WD_ALIGN_PARAGRAPH.CENTER
    vr = vp.add_run(f"{L['verdict_label']}: {verdict}  |  {L['rr_label']}: {rr_score}")
    vr.bold = True
    vr.font.size = Pt(12)

    doc.add_paragraph()
    doc.add_paragraph("─" * 70)
    doc.add_paragraph()

    # -----------------------------------------------------------------------
    # EXECUTIVE SUMMARY
    # -----------------------------------------------------------------------
    add_heading(doc, L["exec"], 1)
    exec_sec = sections.get("executive_summary", "")

    if isinstance(exec_sec, dict):
        add_table(doc, [L["verdict_label"], ""], [
            [L["verdict_label"],  exec_sec.get("verdict", verdict)],
            [L["rr_label"],       str(exec_sec.get("rr_score", rr_score))],
            [L["price_label"],    price_fmt],
            [L["target_label"],   f"{cur_sym}{exec_sec.get('base_target', '—')}"],
            [L["horizon_label"],  exec_sec.get("horizon", "12 months")],
        ])
        add_text_block(doc, exec_sec.get("narrative", ""))
    elif exec_sec:
        add_text_block(doc, exec_sec)
    else:
        # Fall back to top-level fields
        add_table(doc, [L["verdict_label"], ""], [
            [L["verdict_label"],  verdict],
            [L["rr_label"],       str(rr_score)],
            [L["price_label"],    price_fmt],
        ])

    # -----------------------------------------------------------------------
    # SECTION 1 — Business Overview
    # -----------------------------------------------------------------------
    add_heading(doc, L["s1"], 1)
    s1 = sections.get("business_overview", "")
    if isinstance(s1, dict):
        for key, val in s1.items():
            if val:
                p = doc.add_paragraph()
                p.add_run(key.replace("_", " ").title() + ": ").bold = True
                p.add_run(str(val))
    else:
        add_text_block(doc, s1)

    # -----------------------------------------------------------------------
    # SECTION 2 — Financial Performance
    # -----------------------------------------------------------------------
    add_heading(doc, L["s2"], 1)
    s2 = sections.get("financial_performance", "")

    if isinstance(s2, dict):
        add_text_block(doc, s2.get("narrative", ""))

        for table_key, heading_key in [
            ("revenue_table",    "s2_rev"),
            ("margin_table",     "s2_margin"),
            ("cash_flow_table",  "s2_cf"),
            ("balance_sheet",    "s2_bs"),
        ]:
            records = s2.get(table_key)
            if records and isinstance(records, list):
                add_heading(doc, L[heading_key], 2)
                headers, rows = rows_from_list_of_dicts(records)
                if headers:
                    add_table(doc, headers, rows)

        add_text_block(doc, s2.get("fcf_note", ""))
    else:
        add_text_block(doc, s2)

    # -----------------------------------------------------------------------
    # SECTION 3 — Valuation Analysis
    # -----------------------------------------------------------------------
    add_heading(doc, L["s3"], 1)
    s3 = sections.get("valuation_analysis", "")

    if isinstance(s3, dict):
        add_text_block(doc, s3.get("narrative", ""))

        vt = s3.get("valuation_table")
        if vt and isinstance(vt, list):
            add_heading(doc, L["s3_core"], 2)
            headers, rows = rows_from_list_of_dicts(vt)
            if headers:
                add_table(doc, headers, rows)

        sotp = s3.get("sotp_table")
        if sotp and isinstance(sotp, list):
            add_heading(doc, L["s3_sotp"], 2)
            headers, rows = rows_from_list_of_dicts(sotp)
            if headers:
                add_table(doc, headers, rows)
    elif s3:
        add_text_block(doc, s3)
    else:
        # Fall back: render key_metrics table from top level
        key_metrics = data.get("key_metrics", {})
        if key_metrics:
            rows = []
            for metric, info in key_metrics.items():
                if isinstance(info, dict):
                    val = info.get("value")
                    rows.append([
                        metric.replace("_", " ").title(),
                        "—" if val is None else str(val),
                        info.get("grade", "—"),
                        info.get("tag", ""),
                    ])
            if rows:
                add_table(doc, ["Metric", "Value", "Grade", "Tag"], rows)

    # -----------------------------------------------------------------------
    # SECTION 4 — 5-Question Variant View
    # -----------------------------------------------------------------------
    add_heading(doc, L["s4"], 1)
    vv = sections.get("variant_view", {})

    for q_key, heading_key in [("q1", "q1"), ("q2", "q2"), ("q3", "q3"), ("q4", "q4"), ("q5", "q5")]:
        add_heading(doc, L[heading_key], 2)
        # Accept both flat keys (variant_view_q1) and nested (variant_view.q1)
        content = sections.get(f"variant_view_{q_key}", vv.get(q_key, ""))

        if q_key == "q2":
            # Check for structured catalyst table
            catalysts = sections.get("variant_view_q2_catalysts", vv.get("q2_catalysts"))
            if catalysts and isinstance(catalysts, list) and isinstance(catalysts[0], dict):
                headers, rows = rows_from_list_of_dicts(catalysts)
                add_table(doc, headers, rows)
        if q_key == "q5":
            conditions = sections.get("variant_view_q5_conditions", vv.get("q5_conditions"))
            if conditions and isinstance(conditions, list):
                for cond in conditions:
                    doc.add_paragraph(f"• {cond}" if isinstance(cond, str) else str(cond),
                                      style="List Bullet")

        add_text_block(doc, content)

    # -----------------------------------------------------------------------
    # SECTION 5 — Precision Risk Analysis
    # -----------------------------------------------------------------------
    add_heading(doc, L["s5"], 1)
    risks = sections.get("precision_risks", [])

    if risks and isinstance(risks, list):
        if isinstance(risks[0], dict):
            # Use first record's keys as headers if standard; otherwise use fixed headers
            if "risk" in risks[0] or "name" in risks[0]:
                fixed_headers = ["Risk", "Mechanism", "EBITDA Impact", "Probability", "Mitigation"]
                risk_rows = [
                    [
                        r.get("risk", r.get("name", "—")),
                        r.get("mechanism", "—"),
                        r.get("ebitda_impact", r.get("impact", "—")),
                        r.get("probability", "—"),
                        r.get("mitigation", "—"),
                    ]
                    for r in risks
                ]
                add_table(doc, fixed_headers, risk_rows)
            else:
                headers, rows = rows_from_list_of_dicts(risks)
                add_table(doc, headers, rows)
        else:
            for r in risks:
                doc.add_paragraph(str(r))

    macro = sections.get("macro_risk", "")
    if macro:
        add_heading(doc, L["s5_macro"], 2)
        add_text_block(doc, macro)

    # -----------------------------------------------------------------------
    # SECTION 6 — Investment Scenarios
    # -----------------------------------------------------------------------
    add_heading(doc, L["s6"], 1)
    scenarios = data.get("scenarios", {})

    if scenarios:
        bull = scenarios.get("bull", {})
        base = scenarios.get("base", {})
        bear = scenarios.get("bear", {})

        bull_prob = int((bull.get("probability") or 0) * 100)
        base_prob = int((base.get("probability") or 0) * 100)
        bear_prob = int((bear.get("probability") or 0) * 100)

        def fmt_target(t):
            if t is None:
                return "—"
            return f"{cur_sym}{t:,.0f}" if currency == "KRW" else f"{cur_sym}{t}"

        def fmt_ret(r):
            if r is None:
                return "—"
            sign = "+" if float(r) >= 0 else ""
            return f"{sign}{r}%"

        add_table(doc, ["", L["bull"], L["base"], L["bear"]], [
            [L["prob_row"],       f"{bull_prob}%",             f"{base_prob}%",             f"{bear_prob}%"],
            [L["target_row"],     fmt_target(bull.get("target")),  fmt_target(base.get("target")),  fmt_target(bear.get("target"))],
            [L["return_row"],     fmt_ret(bull.get("return_pct")),  fmt_ret(base.get("return_pct")),  fmt_ret(bear.get("return_pct"))],
            [L["assumption_row"], bull.get("key_assumption", "—"), base.get("key_assumption", "—"), bear.get("key_assumption", "—")],
        ])

        # R/R formula
        bull_ret = bull.get("return_pct", 0) or 0
        base_ret = base.get("return_pct", 0) or 0
        bear_ret = bear.get("return_pct", 0) or 0

        rr_p = doc.add_paragraph()
        rr_p.add_run(f"{L['rr_label']}: {rr_score}").bold = True
        rr_p.add_run(
            f"\nR/R = ({bull_ret}% × {bull_prob}% + {base_ret}% × {base_prob}%) "
            f"/ |{bear_ret}% × {bear_prob}%| = {rr_score}"
        )

        # Scenario narratives
        inv_sec = sections.get("investment_scenarios", {})
        if isinstance(inv_sec, dict):
            narratives = inv_sec.get("narratives", {})
            for case_key, label in [("bull", L["bull"]), ("base", L["base"]), ("bear", L["bear"])]:
                if narratives.get(case_key):
                    p = doc.add_paragraph()
                    p.add_run(f"{label}: ").bold = True
                    p.add_run(narratives[case_key])
        elif isinstance(inv_sec, str) and inv_sec:
            add_text_block(doc, inv_sec)

    # -----------------------------------------------------------------------
    # SECTION 7 — Peer Comparison
    # -----------------------------------------------------------------------
    add_heading(doc, L["s7"], 1)
    peers = sections.get("peer_comparison", [])

    if isinstance(peers, list) and peers:
        headers, rows = rows_from_list_of_dicts(peers) if isinstance(peers[0], dict) else (["Peer"], [[str(p)] for p in peers])
        add_table(doc, headers, rows)

    peer_narrative = sections.get("peer_comparison_narrative", "")
    if peer_narrative:
        add_text_block(doc, peer_narrative)

    # -----------------------------------------------------------------------
    # SECTION 8 — Management & Corporate Governance
    # -----------------------------------------------------------------------
    add_heading(doc, L["s8"], 1)
    s8 = sections.get("management_governance", "")

    if isinstance(s8, dict):
        for key, val in s8.items():
            if val:
                p = doc.add_paragraph()
                p.add_run(key.replace("_", " ").title() + ": ").bold = True
                p.add_run(str(val))
    else:
        add_text_block(doc, s8)

    # -----------------------------------------------------------------------
    # SECTION 9 — Quality of Earnings
    # -----------------------------------------------------------------------
    add_heading(doc, L["s9"], 1)
    qoe = sections.get("quality_of_earnings", sections.get("qoe_summary", ""))

    if isinstance(qoe, dict):
        bridge = qoe.get("ebitda_bridge")
        if bridge and isinstance(bridge, list):
            add_heading(doc, L["s9_bridge"], 2)
            headers, rows = rows_from_list_of_dicts(bridge)
            if headers:
                add_table(doc, headers, rows)

        add_text_block(doc, qoe.get("narrative", ""))

        fcf = qoe.get("fcf_conversion")
        if fcf:
            p = doc.add_paragraph()
            p.add_run("FCF Conversion: ").bold = True
            p.add_run(str(fcf))

        sustainability = qoe.get("earnings_sustainability", "")
        if sustainability:
            doc.add_paragraph(sustainability)
    else:
        add_text_block(doc, qoe)

    # -----------------------------------------------------------------------
    # SECTION 10 — What Would Make Me Wrong
    # -----------------------------------------------------------------------
    add_heading(doc, L["s10"], 1)
    wrong = sections.get("what_would_make_me_wrong", "")

    if isinstance(wrong, dict):
        assumptions = wrong.get("assumptions", [])
        for i, assumption in enumerate(assumptions, 1):
            if isinstance(assumption, dict):
                add_heading(doc, f"Assumption {i}: {assumption.get('assumption', '')}", 2)
                for field, label in [
                    ("if_wrong",           "If wrong"),
                    ("monitoring_indicator", "Monitoring indicator"),
                    ("probability",         "Probability of being wrong"),
                ]:
                    if assumption.get(field):
                        p = doc.add_paragraph()
                        p.add_run(label + ": ").bold = True
                        p.add_run(str(assumption[field]))
            else:
                doc.add_paragraph(str(assumption))
        pre_mortem = wrong.get("pre_mortem", "")
        if pre_mortem:
            p = doc.add_paragraph()
            p.add_run("Pre-Mortem: ").bold = True
            p.add_run(pre_mortem)

    elif isinstance(wrong, list):
        for i, item in enumerate(wrong, 1):
            if isinstance(item, dict):
                add_heading(doc, f"Assumption {i}: {item.get('assumption', '')}", 2)
                for field, label in [
                    ("if_wrong",           "If wrong"),
                    ("monitoring_indicator", "Monitoring indicator"),
                    ("probability",         "Probability of being wrong"),
                ]:
                    if item.get(field):
                        p = doc.add_paragraph()
                        p.add_run(label + ": ").bold = True
                        p.add_run(str(item[field]))
            else:
                doc.add_paragraph(str(item))
        pre_mortem = sections.get("pre_mortem", "")
        if pre_mortem:
            p = doc.add_paragraph()
            p.add_run("Pre-Mortem: ").bold = True
            p.add_run(pre_mortem)
    else:
        add_text_block(doc, wrong)

    # -----------------------------------------------------------------------
    # APPENDIX — Data Sources & Confidence
    # -----------------------------------------------------------------------
    add_heading(doc, L["appendix"], 1)
    data_sources = sections.get("data_sources", data.get("data_sources", []))

    if data_sources and isinstance(data_sources, list) and isinstance(data_sources[0], dict):
        headers, rows = rows_from_list_of_dicts(data_sources)
        add_table(doc, headers, rows)

    dq = data.get("data_quality_used", {})
    if dq:
        p = doc.add_paragraph()
        p.add_run("Data Quality Summary: ").bold = True
        p.add_run(
            f"Grade A: {dq.get('grade_A_count', 0)} | "
            f"Grade B: {dq.get('grade_B_count', 0)} | "
            f"Grade C: {dq.get('grade_C_count', 0)} | "
            f"Grade D (excluded): {dq.get('grade_D_count', 0)} | "
            f"Overall: {dq.get('overall_grade', '—')}"
        )
        excl = dq.get("exclusions", [])
        if excl:
            p2 = doc.add_paragraph()
            p2.add_run("Exclusions: ").bold = True
            for e in excl:
                if isinstance(e, dict):
                    p2.add_run(f"\n  • {e.get('metric', '—')}: {e.get('reason', '—')}")

    mode_str = (
        "Enhanced (Financial Datasets MCP active)"
        if data_mode == "enhanced"
        else "Standard (Web-only)"
    )
    doc.add_paragraph(f"Data Mode: {mode_str}")

    # -----------------------------------------------------------------------
    # DISCLAIMER
    # -----------------------------------------------------------------------
    doc.add_paragraph()
    doc.add_paragraph("─" * 70)

    disc_p = doc.add_paragraph()
    disc_run = disc_p.add_run(L["disclaimer"])
    disc_run.font.size = Pt(8)
    disc_run.font.color.rgb = COLOR_DISCLAIMER

    gen_p = doc.add_paragraph()
    gen_run = gen_p.add_run(
        f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')} UTC  |  "
        f"AI Research Assistant  |  Data Mode: {mode_str}"
    )
    gen_run.font.size = Pt(8)
    gen_run.font.color.rgb = COLOR_GENERATED

    # -----------------------------------------------------------------------
    # SAVE
    # -----------------------------------------------------------------------
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    doc.save(output_path)
    print(f"DOCX saved: {output_path}")
    return output_path


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    # Repo-root import for env-var-aware path resolution.
    _repo_root = pathlib.Path(__file__).resolve().parents[4]
    if str(_repo_root) not in sys.path:
        sys.path.insert(0, str(_repo_root))
    from tools.paths import data_path  # noqa: E402

    parser = argparse.ArgumentParser(description="Generate Mode D Investment Memo as DOCX")
    parser.add_argument(
        "--input", default=str(data_path("analysis-result.json")),
        help="Path to a run-local analysis-result.json"
    )
    parser.add_argument(
        "--output", default=None,
        help="Output .docx path (default: auto-generated from ticker/date)"
    )
    args = parser.parse_args()

    if not os.path.exists(args.input):
        print(f"ERROR: Input file not found: {args.input}")
        sys.exit(1)

    with open(args.input, "r", encoding="utf-8") as f:
        data = json.load(f)

    if args.output:
        output_path = args.output
    else:
        ticker    = data.get("ticker", "UNKNOWN")
        lang      = (data.get("output_language") or "en").upper()
        date_str  = data.get("analysis_date", datetime.now().strftime("%Y-%m-%d"))
        output_path = str(data_path("reports", f"{ticker}_D_{lang}_{date_str}.docx"))

    generate_docx(data, output_path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
